<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DDTInternalTest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ac6b75b2-5d08-4a8d-8d85-e44d43a65567</testSuiteGuid>
   <testCaseLink>
      <guid>62379739-ce01-4ac0-a335-a07c93457cb7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LoginTest</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a3870318-b712-4b5d-8e16-2a62615bb1e1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DDTInternalData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a3870318-b712-4b5d-8e16-2a62615bb1e1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>30236b7f-0b72-46ac-9418-28c54d1a0e80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a3870318-b712-4b5d-8e16-2a62615bb1e1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>3b4e4020-2ba4-441e-b072-36222e9cf520</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
